docker run -d --name gsmpc --network host --restart always -v /var/lib/docker/gsmpc:/gsmpc anyswap/gsmpc --bootnodes "enode://ip@port" --port 12345 --rpcport 23456
docker exec gsmpc gsmpc-client --cmd ACCEPTREQADDR --url http://127.0.0.1:23456 --keystore keystore --passwd "123456" --key 0x...
